//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductPurchase
    {
        public int ProductPurchaseId { get; set; }
        public int SupplierId { get; set; }
        public Nullable<decimal> TotalET { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> TaxId { get; set; }
        public Nullable<decimal> NetTotal { get; set; }
        public string Method { get; set; }
        public Nullable<decimal> Due { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string ReceiptNo { get; set; }
    }
}
