//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRolePermission
    {
        public int RolePermissionId { get; set; }
        public int RoleId { get; set; }
        public Nullable<int> InterfaceId { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Archived { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
