//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSubCategory
    {
        public int SubCategoryId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string SubCategoryName { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string Description { get; set; }
    }
}
