//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserDetail
    {
        public int UserDetailId { get; set; }
        public string CNIC { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> City { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<int> TotalLogin { get; set; }
        public Nullable<System.DateTime> ChangePasswordDate { get; set; }
        public Nullable<bool> EmialConfirmed { get; set; }
        public string EmailCode { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Archived { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
